#!/usr/bin/env bash

# Description: Set the selected image as wallpaper using nitrogen. 
#
# Shell: POSIX Compliant
# Author: juacq97

if [ "$(mimetype --output-format %d $(cat ~/.nnncp) | cut -d " " -f 2)" == "image" ]; then
    nitrogen --set-zoom-fill --save $(cat ~/.nnncp)
else
    echo "Select a image"
fi
