#!/bin/sh

if ! [ -z "$1" ]; then
    if [ $(mimetype --output-format %m $1 | awk -F '/' '{print $1}') == "image" ]; then
	nitrogen --set-zoom-fill --save $1
	notify-send -a "nnn" "Wallpaper changed!"
    else
	notify-send -a "nnn" "You need to select a image"
    fi
fi
