#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII
bspc config border_width         4
bspc config border_radius       10
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color '#5294E2'

bspc rule -a Gimp desktop='^6' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Spotify desktop='^10'
bspc rule -a libreoffice desktop='^4' follow=on
bspc rule -a Lxappareance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a qt5ct state=floating
bspc rule -a virtualbox state=floating
bspc rule -a Gucharmap state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a MPlayer state=floating
bspc rule -a Sxiv state=floating

# Autostart
nitrogen --restore; sleep 1; compton -b &
compton -b --config ~/.config/compton.conf &
nm-applet &
xfce4-power-manager &
pamac-tray &
clipit &
conky -c ~/conkys/shortcuts_i3 &
conky -c ~/conkys/cpu-ram &
conky -c ~/conkys/pie/pie_clock &
xautolock -locker i3lock-fancy -f Fantasque-Sans-Mono-Regular -t Contraseña, mode "default" &
tup-id ff-theme-util &
tup-id fix_xcursor &
emacs --fg-daemon &
~/.config/polybar/polybar_launch.sh &
fluxgui &
/usr/lib/kdeconnectd &
indicator-kdeconnect &
pacmd load-module module-remap-sink sink_name=mono master=alsa_output.pci-0000_00_14.2.analog-stereo channels=2 channel_map=mono,mono &
xrdb -load ~/.Xresources &
numlockx on &
