#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8
bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color '#BF6715'
bspc config presel_feedback_color '#BF6715'

bspc rule -a Gimp desktop='^6' follow=on
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Spotify desktop='^8'
bspc rule -a libreoffice desktop='^4' follow=on state=tiled
bspc rule -a Lxappareance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a qt5ct state=floating
bspc rule -a virtualbox state=floating
bspc rule -a Gucharmap state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a MPlayer state=floating
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Emacs:capture state=floating sticky=on

# Autostart
# Crea un archivo de bloqueo en /tmp al arrancar y ejecuta todo, en siguientes ejecuciones de bspwmrc, el archivo existirá, y por lo tanto, no se ejecutará nada, evitando instancias repetidas

#startup_lock_file=/tmp/bspwm-startup.lock
#if [ ! -f $startup_lock_file ]; then
#    echo "dummy" > $startup_lock_file
    
# Agregar las aplicaciones de autoarranque debajo de esta línea
#==========================================================================================================================
if [ -z "$(pidof nitrogen)" ]; then
    nitrogen --restore; sleep 1; compton -b &
fi

if [ -z "$(pidof compton)" ]; then
    compton -b --config ~/.config/compton.conf &
fi

if [ -z "$(pidof nm-applet)" ]; then
    nm-applet &
fi

if [ -z "$(pidof xfce4-power-manager)" ]; then
    xfce4-power-manager &
fi

#pamac-tray &

if [ -z "$(pidof clipit)" ]; then
    clipit &
fi

if [ -z "$(pidof conky)" ]; then
    #conky -c ~/conkys/shortcuts_i3 &
    conky -c ~/conkys/cpu-ram &
    conky -c ~/conkys/pie/pie_clock &
fi

#if  [ -z "$(pidof xautolock)"]; then
#    xautolock -locker i3lock-fancy -f Fantasque-Sans-Mono-Regular -t Contraseña, mode "default" &
#fi

if [ -z "$(pidof emacs)" ]; then
    emacs --daemon &
fi

if [ -z "$(pidof polybar)" ]; then
    polybar -c ~/.config/polybar/config example -r &
fi

#fluxgui &


if [ -z "$(pido kdeconnectd)" ]; then
    /usr/lib/kdeconnectd &
fi

killall redshift
redshift &
pacmd load-module module-remap-sink sink_name=mono master=alsa_output.pci-0000_00_14.2.analog-stereo channels=2 channel_map=mono,mono &
xrdb -load ~/.Xresources &
numlockx on &

#==========================================================================================================================
