#!/bin/sh

var=$(echo -e "Apagar\nBloquear\nReiniciar\nCerrar sesión\nCancelar" | rofi -dmenu -theme material -theme-str '#window {height: 350; }' -eh 1 -i -p "¿Desea salir?") 


if [ "$var" == 'Apagar' ]
then
    rm /tmp/bspwm-startup.lock
    systemctl poweroff
elif [ "$var" == 'Bloquear' ]
then
    blurlock
elif [ "$var" == 'Reiniciar' ]
then
    rm /tmp/bspwm-startup.lock
    systemctl reboot
elif [ "$var" == 'Cerrar sesión' ]
then
    rm /tmp/bspwm-startup.lock
    bspc quit
elif [ "$var" == 'Cancelar' ]
then
    echo cancelado
fi


#-theme-str '#window {fullscreen: true; } #mainbox {padding: 300 300px;}' 
