#! /bin/sh

var=$(echo -e "Push\nPull\nSync \nSync " | rofi -dmenu -theme material -theme-str '#window {height: 300; weight: 20; }' -eh 1 -i ) 

if [ "$var" == "Push" ]
then
    rclone copy ~/Drive google: -u -v
elif [ "$var" == "Pull" ]
then
    rclone copy google: ~/Drive -u
elif [ "$var" == "Sync " ]
then
    rclone sync google: ~/Drive
elif [ "$var" == "Sync " ]
then
    rclone sync ~/Drive google:
fi

    
    
    
    
    
