#! /bin/sh

var=$(echo -e "1) Push\n2) Pull\n3) Sync \n4) Sync " | rofi -dmenu -theme material -theme-str '#window {height: 300; weight: 20; }' -eh 1 -i ) 

if [ "$var" == "1) Push" ]
then
    notify-send -a "Rclone" "Subiendo archivos"
    rclone copy ~/Drive google: -u -v
    notify-send -a "Rclone" "Archivos subidos a la nube"
elif [ "$var" == "2) Pull" ]
then
    notify-send -a "Rclone" "Descargando archivos"
    rclone copy google: ~/Drive -u
    notify-send -a "Rclone" "Archivos descargados de la nube"
elif [ "$var" == "3) Sync " ]
then
    notify-send -a "Rclone" "Clonando en la nube"
    rclone sync google: ~/Drive
    notify-send -a "Rclone" "Carpeta local clonada en la nube"
elif [ "$var" == "4) Sync " ]
then
    notify-send -a "Rclone" "Clonando en local"
    rclone sync ~/Drive google:
    notify-send -a "Rclone" "Carpeta remota clonada en local"
fi

    
    
    
    
    
